# Generated by Django 2.2.17 on 2022-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
            ],
        ),
    ]
